/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: KangaroOz 3D (https://sketchfab.com/KangaroOz-3D)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/macbook-pro-2021-37763335f74b497e91906986b170b5d1
Title: MacBook Pro 2021
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const MacBookPro = ({ brightness = 1, ...props }) => {
  const { nodes, materials } = useGLTF("/models/macbookpro.glb");

  const screenTxt = useTexture("textures/desk/screen_2.png");
  const brightColor = new THREE.Color(brightness, brightness, brightness);

  return (
    <group {...props} dispose={null}>
      <group position={[0.121, 0.007, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.MacBookPro}
        >
          <meshMatcapMaterial
            map={screenTxt}
            color={brightColor}
            opacity={1}
            transparent={false}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.MacBookPro}
        ></mesh>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.MacBookPro}
      ></mesh>
    </group>
  );
};

useGLTF.preload("/models/macbookpro.glb");

export default MacBookPro;
