/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: bioMorph (https://sketchfab.com/biomorph)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/voxel-turntable-495a62d8f03f48788ae31e9d50648b9c
Title: voxel Turntable
*/

import React, { useRef } from 'react'
import { Float, useGLTF } from '@react-three/drei'

const ReactLogo = (props) => {
  const { nodes, materials } = useGLTF('/models/voxel_turntable.glb')
  return (
    <Float  dispose={null}>  

    <group scale={0.01} {...props}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.palette}
        rotation={[-Math.PI / 2, 0, 0]}
        />
    </group>
        </Float>
  )
}

useGLTF.preload('/models/voxel_turntable.glb')

export default ReactLogo